# Stage 1 – Generate static site with MkDocs
FROM squidfunk/mkdocs-material AS builder
WORKDIR /docs
COPY docs/ .
RUN mkdocs build

# Stage 2 – Serve static site with Nginx
FROM nginx:alpine
COPY --from=builder /docs/site /usr/share/nginx/html
EXPOSE 8081
